<template>
  <div :class="yeslog == '0' ? 'yscon' : 'ysconf'">
    <h1>STAKING</h1>
    <p>
      Our system is currently processing for the next epoch, please continue to
      check back.
    </p>
    <div class="yscbox flex jus">
      <div :class="yeslog == '0' ? 'yscbl flex' : 'yscblnone'">
        <div class="yscblcon flex flexcol">
          <div class="yscbltop flex">
            <img src="../assets/logos.png" alt="" />
            <h1>SuperVerse DAO Staking</h1>
          </div>
          <div class="yscbltxt">
            SuperVerse DAO staking allows community members to stake SUPER
            tokens and NFTs in order to receive ETH rewards generated by fees
            and royalties collected from SuperVerse DAO products, and eventually
            qualify to participate in DAO governance.
            <a href="https://superverse.cool/staking-terms/" class="font-bold"
              >Staking Terms apply.</a
            >
          </div>
          <div class="yscblk yscblkh flex jus">
            <div class="yscblkf yscblkfb flex flexcol">
              <p>If You Staked</p>
              <div class="yscblkje flex">
                <img src="../assets/logos.png" alt="" />
                <span>1,761.16</span>
              </div>
              <div class="yscblkd">$1,000</div>
            </div>
            <div class="yscblkf yscblkfb flex flexcol">
              <p>Est. 24h Rewards</p>
              <div class="yscblkje flex">
                <img
                  style="margin-left: 0"
                  src="../assets/eth-color.svg"
                  alt=""
                />
                <span class="fontblue">0.000029</span>
              </div>
              <div class="yscblkd">$0.07</div>
            </div>
          </div>
          <div class="yscbltcon">
            Our staking interface helps estimate rewards and draft blockchain
            transactions for you to review and execute at your discretion. See
            our
            <a href="https://superverse.cool/staking-terms/" class="font-bold"
              >Staking Terms</a
            >
            for more. Staking rewards estimates are based on current information
            from the public DAO Staker contract. Estimates are based on the
            total value of Pooled Assets and Rewards available and may change
            block-by-block. You may use our Interface to draft requests to stake
            or unstake $SUPER, EllioTrades NFTs, or SuperFarm Genesis NFTs to
            and from the DAO Staker at anytime, but you must review any
            transaction in your Wallet for accuracy before choosing to sign any
            transaction. Only you can review and authorize transactions and any
            transaction or ‘gas’ fees your Wallet may assess.
          </div>
        </div>
      </div>
      <div :class="yeslog == '1' ? 'yscbl flex' : 'yscblnone'">
        <div class="yscblcon flex flexcol">
          <div class="yscbltop flex">
            <img src="../assets/logos.png" alt="" />
            <h1>SuperVerse DAO Staking</h1>
          </div>
          <div class="yscbltxt">
            SuperVerse DAO staking allows community members to stake SUPER
            tokens and NFTs in order to receive ETH rewards generated by fees
            and royalties collected from SuperVerse DAO products, and eventually
            qualify to participate in DAO governance.
            <a href="https://superverse.cool/staking-terms/" class="font-bold"
              >Staking Terms apply.</a
            >
          </div>
          <div class="yscbltinpx flex flexcol">
            <div class="yscbltinpxy flex jus">
              <span>Total Staking Power</span>
              <div>0.00</div>
            </div>
            <div class="yscbltinpxt flex yscblk">
              <div class="yscblkf flex flexcol">
                <p>Your Staked SUPER</p>
                <div class="yscblkje flex">
                  <img src="/img/logos.d9572e57.png" alt="" /><span>0.00</span>
                </div>
                <div class="yscblkd">$0.00</div>
              </div>
              <div
                @click="statcs('1')"
                style="height: 100%"
                class="yscblkf yscblkfa flex flexcol"
              >
                <p>Your Staked NFTs (0)</p>
              </div>
              <div class="yscblkf flex flexcol">
                <p>Est. 24h Rewards</p>
                <div class="yscblkje flex">
                  <img
                    style="margin-left: 0"
                    src="/img/eth-color.f9154fe1.svg"
                    alt=""
                  /><span class="fontblue">0.000000</span>
                </div>
                <div class="yscblkd">$0.00</div>
              </div>
            </div>
            <div class="yscbltinpxs flex jus">
              <span>Total Pending Rewards</span>
              <div class="yscbltinpxsr flex flexcol">
                <div class="yscbltinpxsrt flex">
                  <img src="../assets/eth-color.svg" alt="" />
                  <span>0.0000000000</span>
                </div>
                <span>$0.00</span>
              </div>
            </div>
            <button class="yscbltinpxf">Claim Rewards</button>
          </div>
          <div class="yscbltcon">
            Our staking interface helps estimate rewards and draft blockchain
            transactions for you to review and execute at your discretion. See
            our
            <a href="https://superverse.cool/staking-terms/" class="font-bold"
              >Staking Terms</a
            >
            for more. Staking rewards estimates are based on current information
            from the public DAO Staker contract. Estimates are based on the
            total value of Pooled Assets and Rewards available and may change
            block-by-block. You may use our Interface to draft requests to stake
            or unstake $SUPER, EllioTrades NFTs, or SuperFarm Genesis NFTs to
            and from the DAO Staker at anytime, but you must review any
            transaction in your Wallet for accuracy before choosing to sign any
            transaction. Only you can review and authorize transactions and any
            transaction or ‘gas’ fees your Wallet may assess.
          </div>
        </div>
      </div>
      <div class="yscbr flex">
        <div class="yscbrbox">
          <div class="yscbrbtop flex">
            <button
              @click="changetab('0')"
              :class="
                statab == '0' ? 'yscbrbttab yscbrbttabactive' : 'yscbrbttab '
              "
            >
              STAKE
            </button>
            <button
              @click="changetab('1')"
              :class="
                statab == '1' ? 'yscbrbttab yscbrbttabactive' : 'yscbrbttab'
              "
            >
              UNSTAKE
            </button>
          </div>
          <div :class="statab == '0' ? 'yscbrbcon' : 'yscbrbconnone'">
            <div class="yscbrbcnr flex flexcol">
              <div class="yscbrbcnry">
                <p>Stake SUPER</p>
                <span
                  >Stake your SUPER tokens to start earning ETH rewards.</span
                >
                <div class="yscbrbinp">
                  <input @input="sinput()" type="text" v-model="inpval" />
                  <span @click="stabalance()">MAX</span>
                </div>
                <span style="margin: 0.5rem 0 0"
                  >Available: {{ userbla }} SUPER</span
                >
              </div>
              <div class="yscbrbcnry">
                <p>Stake SUPER</p>
                <span
                  >Stake your SUPER tokens to start earning ETH rewards.</span
                >
                <div class="yscbrbinp">
                  <input @input="sinput()" type="text" v-model="inpvalt" />
                  <span @click="statbalance()">MAX</span>
                </div>
                <span style="margin: 0.5rem 0 0"
                  >Available: {{ userusdtbla }} SUPER</span
                >
              </div>
              <!-- <div class="yscbrbcnrt flex flexcol">
                <div class="yscbrbcnrttop">
                  <p>Stake NFTs</p>
                  <span
                    >Stake your eligible NFTs to start earning ETH
                    rewards.</span
                  >
                </div>
                <div class="yscbrbcnrtbot flex">
                  <button>Select NFTs</button>
                  <div>Eligible: 0</div>
                </div>
              </div> -->
              <button
                :class="
                  yeslog == '0' ? 'yscbrbcnrs yscbrbcnrsno' : 'yscbrbcnrs'
                "
              >
                Stake
              </button>
            </div>
          </div>
          <div :class="statab == '1' ? 'yscbrbcon' : 'yscbrbconnone'">
            <div class="yscbrbcnr flex flexcol">
              <div class="yscbrbcnry">
                <p>Unstake SUPER</p>
                <span
                  >Unstaking SUPER will automatically claim your ETH rewards on
                  the same transaction.</span
                >
                <div class="yscbrbinp">
                  <input @input="unsinput()" type="text" v-model="inpval" />
                  <span @click="stabalance()">MAX</span>
                </div>
                <span style="margin: 0.5rem 0 0"
                  >Staked: {{ userbla }} SUPER</span
                >
              </div>
              <div class="yscbrbcnry">
                <p>Unstake SUPER</p>
                <span
                  >Unstaking SUPER will automatically claim your ETH rewards on
                  the same transaction.</span
                >
                <div class="yscbrbinp">
                  <input @input="unsinput()" type="text" v-model="inpvalt" />
                  <span @click="statbalance()">MAX</span>
                </div>
                <span style="margin: 0.5rem 0 0"
                  >Staked: {{ userusdtbla }} SUPER</span
                >
              </div>
              <!-- <div class="yscbrbcnrt flex flexcol">
                <div class="yscbrbcnrttop">
                  <p>Unstake NFTs</p>
                  <span
                    >Unstaking NFTs will automatically claim your ETH rewards on
                    the same transaction.</span
                  >
                </div>
                <div class="yscbrbcnrtbot flex">
                  <button>Select NFTs</button>
                  <div>Staked: 0</div>
                </div>
              </div> -->
              <button
                :class="
                  yeslog == '0' ? 'yscbrbcnrs yscbrbcnrsno' : 'yscbrbcnrs'
                "
              >
                Unstake
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div
    @click="statcs('0')"
    :class="istcshow == '0' ? 'ysbgtcnone' : 'ysbgtc flex'"
  >
    <div @click.stop="isstop()" class="ysbgtcbox">
      <img @click="statcs('0')" src="../assets/close-line.svg" alt="" />
      <div class="ysbgtcbtop">Your Staked NFTs (0)</div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import bus from "../utils/bus";
let yeslog = ref("0");
let statab = ref("0");
let inpval = ref("0");
let inpvalt = ref("0");
let userbla = ref("0");
let userusdtbla = ref("0");
let istcshow = ref("0");
onMounted(() => {
  bus.$on("qbbalance", (val) => {
    if (val != "") {
      yeslog.value = "1";
      userbla.value = Number(val).toFixed(2);
    }
  });
  bus.$on("qbusdtbalance", (val) => {
    if (val != "") {
      yeslog.value = "1";
      userusdtbla.value = Number(val).toFixed(2);
    }
  });
  bus.$on("logout", (val) => {
    if (val == "out") {
      yeslog.value = "0";
    }
  });
  if (localStorage.getItem("xhladd")) {
    yeslog.value = "1";
  }
  if (localStorage.getItem("xhlbalance")) {
    userbla.value = Number(localStorage.getItem("xhlbalance")).toFixed(2);
  }
  if (localStorage.getItem("xhlusdtbalance")) {
    userusdtbla.value = Number(localStorage.getItem("xhlusdtbalance")).toFixed(
      2
    );
  }
});
let changetab = (str) => {
  statab.value = str;
};
let stabalance = () => {
  inpval.value = Number(userbla.value).toFixed(2);
};
let statbalance = () => {
  inpvalt.value = Number(userusdtbla.value).toFixed(2);
};
let unsinput = () => {
  inpvalt.value = inpvalt.value.replace(/[^\d.]/g, "");
};
let sinput = () => {
  inpval.value = inpval.value.replace(/[^\d.]/g, "");
};
let statcs = (str) => {
  istcshow.value = str;
};
let isstop = () => {
  console.log("add");
};
</script>

<style scoped>
.yscon {
  width: 100%;
  height: calc(100vh - 7.25rem);
  background: rgb(30, 37, 43);
  padding-top: 8.5rem;
}
.yscblkh {
  height: 10rem;
}
.yscblk > .yscblkfb {
  flex-grow: 0;
}
.yscblkfb {
  width: 45%;
  height: 100%;
}
.ysconf {
  width: 100%;
  background: rgb(30, 37, 43);
  padding-top: 8.5rem;
  height: auto;
  box-sizing: border-box;
}
.ymainhy .yscon {
  background: white;
}
.ymainhy .ysconf {
  background: white;
}
.yscon > h1 {
  display: block;
  font-size: 72px;
  line-height: 80px;
  font-family: "Poppins";
  text-align: center;
  color: white;
}
.yscon > p {
  display: block;
  color: #6e757c;
  font-family: "Interl";
  font-size: 16px;
  font-weight: 500;
  line-height: 24px;
  text-align: center;
  margin: 1.5rem 0 3rem 0;
}
.ysconf > h1 {
  display: block;
  font-size: 72px;
  line-height: 80px;
  font-family: "Poppins";
  text-align: center;
  color: white;
}
.ysconf > p {
  display: block;
  color: #6e757c;
  font-family: "Interl";
  font-size: 16px;
  font-weight: 500;
  line-height: 24px;
  text-align: center;
  margin: 1.5rem 0 3rem 0;
}
.yscbox {
  width: 98rem;
  height: auto;
  padding: 2rem 2rem 2rem 2.5rem;
  box-sizing: border-box;
  margin: 0 auto;
  border-radius: 1.5rem;
  overflow: hidden;
  align-items: center;
  position: relative;
  background: #2c353d;
}
.ymainhy .yscbox {
  background: white;
}
.yscbl {
  justify-content: center;
  align-items: center;
  box-sizing: border-box;
}
.yscblnone {
  display: none;
}
.yscbr {
  width: 43.875rem;
  backdrop-filter: blur(12px);
  justify-content: center;
  align-items: center;
  box-sizing: border-box;
  position: relative;
  z-index: 10;
}
.yscblcon {
  gap: 0.75rem;
  width: 41.875rem;
}
.yscbltop {
  align-items: center;
  column-gap: 0.5rem;
}
.yscbltop > img {
  width: 3.75rem;
  height: auto;
  margin-left: -1.2rem;
}
.yscbltop > h1 {
  font-family: "Poppins";
  line-height: 2.5rem;
  font-weight: 600;
  font-size: 2.5rem;
  color: white;
}
.ymainhy .yscbltop > h1 {
  color: #000;
}
.yscbltxt {
  font-family: "Interl";
  font-size: 1rem;
  line-height: 1.5rem;
  color: #b3bbca;
}
.ymainhy .yscbltxt {
  color: #6e757c;
}
.font-bold {
  font-family: "Poppins";
  font-size: 700;
  color: #b3bbca;
}
.ymainhy .yscbltxt > .font-bold {
  color: #6e757c;
}
.yscblk {
  column-gap: 0.75rem;
}
.yscblk > div {
  background: rgb(40, 48, 54);
  box-shadow: 0 8px 32px #0000001a;
  padding: 1rem;
  border-radius: 0.5rem;
  gap: 0.75rem;
  align-items: center;
  flex-grow: 1;
  box-sizing: border-box;
  position: relative;
  overflow: hidden;
}
.ymainhy .yscblk > div {
  box-shadow: 0 8px 32px #0000001a;
  background: #f7f7f8;
}
.yscblk > div::before {
  top: -100px;
  left: -100px;
  width: 200px;
  height: 200px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.yscblk > div::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.yscblkf > p {
  font-family: "Interl";
  font-size: 1rem;
  line-height: 1.5rem;
  color: white;
  text-align: center;
}
.ymainhy .yscblkf > p {
  color: #000;
}
.yscblkje {
  align-items: center;
  justify-content: center;
  column-gap: 0.25rem;
}
.yscblkje > img {
  width: 3rem;
  height: auto;
  margin-left: -1rem;
}
.yscblkje > span {
  font-family: "Poppins";
  font-size: 1.5rem;
  line-height: 2rem;
  color: white;
}
.ymainhy .yscblkje > span {
  color: #000;
}

.yscblkd {
  font-size: 0.75rem;
  line-height: 1rem;
  font-family: "Inter";
  color: #b3bbca;
  text-align: center;
}
.ymainhy .yscblkd {
  color: #6e757c;
}
.yscblkje > .fontblue {
  color: rgb(117 117 117) !important;
  z-index: 10;
}
.yscbltcon {
  font-family: "Interl";
  font-size: 0.625rem;
  line-height: 1rem;
  color: #b3bbca;
}
.ymainhy .yscbltcon {
  color: #6e757c;
}
.yscbltcon > .font-bold {
  font-family: "Poppins";
}
.ymainhy .yscbltcon > .font-bold {
  color: #6e757c;
}
.yscbrlg {
  position: absolute;
  width: 1px;
  height: 100%;
  left: 0;
  bottom: 0;
  background-image: radial-gradient(
    circle at 50% 50%,
    rgb(255, 110, 48),
    hsl(208, 18%, 14%)
  );
}
.yscbrbox {
  width: 100%;
  background-color: rgb(36 35 37);
  box-shadow: rgba(255, 255, 255, 0.25) 0px 1px 2px 0px inset,
    rgba(0, 0, 0, 0.72) 0px 8px 12px 0px;
  border-radius: 0.5rem;
  overflow: hidden;
  position: relative;
}
.yscbox::before {
  top: -280px;
  left: -280px;
  width: 560px;
  height: 560px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.yscbox::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.yscbrbtop {
  width: 100%;
  justify-content: center;
  align-items: center;
  position: relative;
  z-index: 10;
}
.yscbrbttab {
  width: 50%;
  font-family: "Interl";
  color: rgb(141, 141, 141);
  outline: 2px solid transparent;
  display: flex;
  justify-content: center;
  align-items: center;
  outline-offset: 2px;
  letter-spacing: 0.05em;
  text-transform: uppercase;
  height: 3rem;
  padding: 0.375rem 0.75rem;
  font-size: 1.125rem;
  line-height: 1.75rem;
  background: rgb(48, 48, 48);
  box-sizing: border-box;
}
.yscbrbttabactive {
  color: white;
  background-color: rgb(36 35 37);
}
.yscbrbcon {
  width: 100%;
  padding: 1.25rem;
  box-sizing: border-box;
  position: relative;
  z-index: 10;
  background-color: rgb(36 35 37);
}
.yscbrbconnone {
  display: none;
}
.yscbrbcnr {
  width: 100%;
  gap: 1.25rem;
}
.yscbrbcnry {
  width: 100%;
  padding: 1.25rem;
  border: 1px solid hsla(0, 0%, 100%, 0.2);
  border-radius: 0.5rem;
  box-sizing: border-box;
}
.yscbrbcnry > p {
  font-family: "Poppins";
  font-size: 1.125rem;
  line-height: 1.75rem;
  color: white;
}
.yscbrbcnry > span {
  display: block;
  font-size: 0.875rem;
  line-height: 1.25rem;
  margin-bottom: 0.5rem;
  color: hsla(0, 0%, 100%, 0.5);
}
.yscbrbinp {
  position: relative;
  width: 100%;
}
.yscbrbinp > input {
  font-family: "Poppins";
  outline: 2px solid transparent;
  outline-offset: 2px;
  border: 1px solid rgb(161 161 170);
  border-radius: 0.75rem;
  background-color: hsla(0, 0%, 100%, 0.1);
  border-radius: 0.5rem;
  padding: 0 1.5rem;
  height: 3rem;
  width: 100%;
  color: white;
  font-size: 1rem;
  line-height: 1.5rem;
  box-sizing: border-box;
}
.yscbrbinp > span {
  font-family: "Interl";
  font-size: 0.875rem;
  line-height: 1.25rem;
  color: white;
  position: absolute;
  top: 50%;
  cursor: pointer;
  transform: translateY(-50%);
  right: 1rem;
}
.yscbrbcnrt {
  width: 100%;
  padding: 1.5rem;
  gap: 0.75rem;
  border: 1px solid hsla(0, 0%, 100%, 0.2);
  border-radius: 0.5rem;
  box-sizing: border-box;
}
.yscbrbcnrttop > p {
  font-family: "Poppins";
  font-size: 1.125rem;
  line-height: 1.75rem;
  color: white;
}
.yscbrbcnrttop > span {
  display: block;
  font-size: 0.875rem;
  line-height: 1.25rem;
  margin-bottom: 0.5rem;
  color: hsla(0, 0%, 100%, 0.5);
}
.yscbrbcnrtbot {
  column-gap: 0.5rem;
  align-items: center;
}
.yscbrbcnrtbot > button {
  font-family: "Poppins";
  box-shadow: inset 0 0 0 2px #f7f7f8bf;
  border-radius: 0.5rem;
  height: 3rem;
  font-weight: 600;
  font-size: 1rem;
  padding: 0 1rem;
  background: transparent;
  cursor: pointer;
  color: #f7f7f8bf;
}
.yscbrbcnrtbot > button:hover {
  background: #f7f7f8bf;
  box-shadow: none;
  color: #272e35;
}
.yscbrbcnrtbot > div {
  font-family: "Interl";
  color: hsla(0, 0%, 100%, 0.5);
  font-size: 0.75rem;
  line-height: 1rem;
}
.yscbrbcnrs {
  width: 100%;
  font-family: "Poppins";
  box-shadow: inset 0 0 0 2px #f7f7f8bf;
  border-radius: 0.5rem;
  height: 3rem;
  font-weight: 600;
  font-size: 1rem;
  background: transparent;
  cursor: pointer;
  color: #f7f7f8bf;
}
.yscbrbcnrsno {
  cursor: not-allowed;
}
.yscbrbcnrs:hover {
  background: #f7f7f8bf;
  box-shadow: none;
  color: #272e35;
}
.yscbltinpx {
  gap: 0.75rem;
}
.yscbltinpxy {
  width: 100%;
  align-items: center;
  border-radius: 0.5rem;
  background: rgb(40, 48, 54);
  box-shadow: 0 8px 32px #0000001a;
  padding: 1rem;
  position: relative;
  box-sizing: border-box;
  overflow: hidden;
}
.yscbltinpxy::before {
  top: -280px;
  left: -280px;
  width: 560px;
  height: 560px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.yscbltinpxy::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.yscbltinpxy > span {
  font-family: "Interl";
  line-height: 1.25rem;
  font-size: 1rem;
  font-weight: 500;
  color: white;
}
.yscbltinpxy > div {
  font-family: "Poppins";
  font-size: 1.5rem;
  line-height: 2rem;
  color: rgb(117 117 117);
  z-index: 10;
}
.yscbltinpxt {
  width: 100%;
  height: 8.75rem;
  align-items: center;
}
.yscblk > .yscblkfa {
  cursor: pointer;
}
.yscblk > .yscblkfa:hover {
  box-shadow: 0 0 #0000, 0 0 #0000, 0 20px 25px -5px rgba(255, 110, 48, 0.5),
    0 8px 10px -6px rgba(255, 110, 48, 0.5);
}
.yscbltinpxs {
  width: 100%;
  align-items: center;
  border-radius: 0.5rem;
  background: rgb(40, 48, 54);
  box-shadow: 0 8px 32px #0000001a;
  padding: 1rem;
  box-sizing: border-box;
  position: relative;
  overflow: hidden;
}
.yscbltinpxs::before {
  top: -280px;
  left: -280px;
  width: 560px;
  height: 560px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.yscbltinpxs::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.yscbltinpxsr {
  gap: 0.25rem;
  align-items: center;
}
.yscbltinpxsr > span {
  font-family: "Interl";
  font-size: 0.75rem;
  line-height: 1rem;
  color: hsla(0, 0%, 100%, 0.5);
}
.yscbltinpxsrt {
  align-items: center;
}
.yscbltinpxsrt > img {
  width: 3rem;
  height: auto;
}
.yscbltinpxsrt > span {
  font-family: "Poppins";
  font-size: 1.5rem;
  line-height: 2rem;
  color: rgb(117 117 117);
  z-index: 10;
}
.yscbltinpxs > span {
  font-family: "Inter";
  line-height: 1.25rem;
  font-size: 1rem;
  font-weight: 500;
  color: white;
}
.yscbltinpxf {
  width: 100%;
  font-family: "Poppins";
  box-shadow: inset 0 0 0 2px #f7f7f8bf;
  border-radius: 0.5rem;
  height: 3rem;
  font-weight: 600;
  font-size: 1rem;
  background: transparent;
  cursor: pointer;
  color: #f7f7f8bf;
}
.yscbltinpxf:hover {
  background: #f7f7f8bf;
  box-shadow: none;
  color: #272e35;
}
.ymainhy .yscbltinpxy > span {
  color: black;
}
.ymainhy .yscbltinpxs > span {
  color: black;
}
.ymainhy .yscbltinpxsr > span {
  color: #6e757c;
}
.ymainhy .yscbltinpxf {
  box-shadow: inset 0 0 0 2px #272e35bf;
  color: #272e35;
}
.ymainhy .yscbltinpxf:hover {
  background: #272e35;
  box-shadow: none;
  color: #f7f7f8;
}
.ysbgtc {
  width: 100vw;
  height: 100vh;
  position: fixed;
  top: 0;
  left: 0;
  z-index: 101;
  background: rgba(0, 0, 0, 0.9);
  justify-content: center;
  align-items: center;
}
.ysbgtcbox {
  width: 40rem;
  height: 50vh;
  box-sizing: border-box;
  background: #2c353d;
  position: relative;
  border-radius: 1.25rem;
  overflow: hidden;
}
.ysbgtcbox::before {
  top: -280px;
  left: -280px;
  width: 560px;
  height: 560px;
  opacity: 0.6;
  filter: blur(278.261px);
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
}
.ysbgtcbox::after {
  content: "";
  position: absolute;
  border-radius: 50%;
  background: linear-gradient(
    135.15deg,
    #ae80dc 1.17%,
    #dc83c3 31.88%,
    #8084dc 65.46%
  );
  right: -194px;
  bottom: -181px;
  width: 390px;
  height: 390px;
  filter: blur(160px);
  opacity: 0.6;
}
.ysbgtcbox > img {
  width: 1.5rem;
  position: absolute;
  top: 1.5rem;
  right: 1.5rem;
  cursor: pointer;
}
.ysbgtcbtop {
  font-family: "Poppins";
  font-size: 1.125rem;
  line-height: 1.75rem;
  color: white;
  text-align: center;
  padding: 1.25rem;
  border-bottom: 1px solid rgb(90, 90, 89);
}
.ysbgtcnone {
  display: none;
}
.ymainhy .ysconf > h1 {
  color: #000;
}
.ymainhy .yscbltinpxy {
  box-shadow: 0 8px 32px #0000001a;
  background: #f7f7f8;
}
.ymainhy .yscbltinpxs {
  box-shadow: 0 8px 32px #0000001a;
  background: #f7f7f8;
}
@media (max-width: 1250px) {
  .yscon {
    height: auto;
    padding-top: 6rem;
  }
  .yscon > h1 {
    font-size: 2.5rem;
    line-height: 3rem;
  }
  .ysconf > h1 {
    font-size: 2.5rem;
    line-height: 3rem;
  }
  .yscon > p {
    font-size: 1rem;
    line-height: 1.5rem;
    margin-bottom: 1.25rem;
  }
  .ysconf > p {
    font-size: 1rem;
    line-height: 1.5rem;
    margin-bottom: 1.25rem;
  }
  .yscbox {
    display: block;
    width: 100%;
    height: auto;
    padding: 0rem;
  }
  .yscblcon {
    width: 100%;
  }
  .yscbl {
    padding: 1rem;
  }
  .yscbltop > h1 {
    font-size: 1.5rem;
    line-height: 2rem;
  }
  .yscblk {
    display: block;
    height: auto;
  }
  .yscblk > div:nth-child(1) {
    margin-bottom: 0.75rem;
  }
  .yscblk > div:nth-child(2) {
    margin-bottom: 0.75rem;
  }
  .yscblkfb {
    width: 100%;
  }
  .yscblkd {
    margin-top: -0.5rem;
  }
  .yscbr {
    padding: 1rem;
    width: 100%;
  }
  .yscbrlg {
    display: none;
  }
  .yscbrbinp > input {
    padding: 0 1.25rem;
  }
  .yscbltinpxt {
    height: auto;
  }
  .yscbltinpxs {
    flex-direction: column;
    justify-content: center;
  }
  .ysbgtcbox {
    width: 95%;
  }
  .ysbgtcbox::before {
    top: -100px;
    left: -100px;
    width: 200px;
    height: 200px;
    opacity: 0.6;
    filter: blur(278.261px);
    content: "";
    position: absolute;
    border-radius: 50%;
    background: linear-gradient(
      135.15deg,
      #ae80dc 1.17%,
      #dc83c3 31.88%,
      #8084dc 65.46%
    );
  }
  .yscbltinpxy::before {
    top: -100px;
    left: -100px;
    width: 200px;
    height: 200px;
    opacity: 0.6;
    filter: blur(278.261px);
    content: "";
    position: absolute;
    border-radius: 50%;
    background: linear-gradient(
      135.15deg,
      #ae80dc 1.17%,
      #dc83c3 31.88%,
      #8084dc 65.46%
    );
  }
}
</style>
